services:
  - type: web
    name: my-play-app
    env: docker
    buildCommand: "sbt dist"
    startCommand: "target/universal/stage/bin/prefcards -Dplay.http.secret.key=$PLAY_SECRET -Dhttp.port=$PORT"
    envVars:
      - key: PLAY_SECRET
        value: "yQhLW7IGEiBhcANVY9FRqX7TsQQ3uf7L/uurw6ENKss="
