services:
  - type: web
    name: prefcards
    env: docker
    region: frankfurter
    buildCommand: sbt compile
    startCommand: sbt run -Dhttp.port=$PORT
    autoDeploy: true
    envVars:
      - key: PORT
        value: "9000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
